#pragma once

#include <windows.h>

//
// Message define
//
inline UINT WM_SHOW_MAIN_WINDOW;
inline UINT WM_HIDE_MAIN_WINDOW;
inline UINT WM_MOVE_CANDIDATE_WINDOW;
inline const UINT WM_CLS_DICT_CACHE = WM_USER + 100;
inline const UINT WM_DELETE_CANDIDATE = WM_USER + 101;
inline const UINT WM_LANGBAR_RIGHTCLICK = WM_USER + 102;
inline const UINT WM_IMEACTIVATE = WM_USER + 103;
inline const UINT WM_IMEDEACTIVATE = WM_USER + 104;
inline const UINT WM_IMESWITCH = WM_USER + 105;
inline const UINT WM_PUNCSWITCH = WM_USER + 106;
inline const UINT WM_DOUBLESINGLEBYTESWITCH = WM_USER + 107;
inline const UINT UPDATE_FTB_STATUS = WM_USER + 108;
inline const UINT WM_PIN_TO_TOP_CANDIDATE = WM_USER + 109;
inline const UINT WM_COMMIT_CANDIDATE = WM_USER + 110;
inline const UINT WM_CLEAR_IME_ENGINE_CACHE = WM_USER + 111;
inline const UINT WM_REFRESH_MENU_SIZE = WM_USER + 112;
inline const UINT WM_FIX_CANDIDATE_POSITION = WM_USER + 113;
inline const UINT WM_CLEAR_CANDIDATE_POSITION = WM_USER + 114;
inline const UINT UPDATE_FTB_ENGLISH_INPUT_MODE = WM_USER + 115;
inline const UINT WM_APPLY_IME_CONFIG = WM_USER + 116;
inline const UINT UPDATE_FTB_CAPS_LOCK = WM_USER + 117;
inline const UINT WM_APPLY_IME_INPUT_SCHEME = WM_USER + 118;
inline const UINT WM_REFRESH_CHARACTER_SET = WM_USER + 119;
inline const UINT WM_PAGE_CANDIDATE = WM_USER + 120;
inline const UINT WM_SHOW_CARET_STATE = WM_USER + 121;
inline const UINT WM_HIDE_CARET_STATE = WM_USER + 122;
inline const UINT WM_MOVE_CARET_STATE = WM_USER + 123;
// 候选框翻页箭头被点击。与 WM_PAGE_CANDIDATE 同参，但不受「鼠标滚轮翻页」开关约束。
inline const UINT WM_PAGE_CANDIDATE_ARROW = WM_USER + 124;

// wParam of WM_PAGE_CANDIDATE / WM_PAGE_CANDIDATE_ARROW; lParam carries how many pages to move.
inline constexpr WPARAM CANDIDATE_PAGE_PREVIOUS = 0;
inline constexpr WPARAM CANDIDATE_PAGE_NEXT = 1;
