#!/usr/bin/env python3
"""Generate checked-in language bindings. --check rejects stale artifacts in CI."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent


def ts_type(rule):
    if "anyOf" in rule:
        return " | ".join(ts_type(branch) for branch in rule["anyOf"])
    if "enum" in rule:
        return " | ".join(json.dumps(value) for value in rule["enum"])
    if rule.get("type") == "array":
        return "Array<" + ts_type(rule["items"]) + ">"
    if rule.get("type") == "object":
        fields = [f'{json.dumps(key)}{"" if key in rule.get("required", []) else "?"}: {ts_type(value)}'
                  for key, value in rule.get("properties", {}).items()]
        if rule.get("additionalProperties"):
            fields.append("[key: string]: unknown")
        return "{ " + "; ".join(fields) + " }"
    return {"integer": "number", "number": "number", "string": "string", "boolean": "boolean"}.get(rule.get("type"), "unknown")


def union(messages):
    entries = []
    for name, spec in messages.items():
        properties = {"type": {"enum": [name]}, "protocolVersion": {"enum": [1]}, **spec.get("properties", {})}
        required = ["type", *spec.get("required", [])]
        if "data" in spec:
            properties["data"] = spec["data"]
            required.append("data")
        entries.append(ts_type({"type": "object", "properties": properties, "required": required,
                                "additionalProperties": spec.get("additionalProperties", False)}))
    return "\n  | ".join(entries)


def generate():
    schema = json.loads((ROOT / "messages.json").read_text())
    compact = json.dumps(schema, ensure_ascii=False, separators=(",", ":"))
    files = {
        "schema.js": "// Generated by generate.py; edit messages.json.\n(function(root) {\n  const schema = " + compact + ";\n  root.MsimeMessageSchema = schema;\n  if (typeof module !== 'undefined' && module.exports) module.exports = schema;\n})(globalThis);\n",
        "schema.h": '#pragma once\n// Generated by generate.py; edit messages.json.\nnamespace metasequoia::webview {\ninline constexpr int Version = ' + str(schema["version"]) + ';\ninline constexpr char SchemaJson[] = R"msime(' + compact + ')msime";\n}\n',
        "runtime.d.ts": "export {};\n",
    }
    types = "// Generated by generate.py; edit messages.json.\nimport './schema.js';\nimport './runtime.js';\n"
    for name, messages in [("ClientMessage", schema["client"]), ("ServerMessage", schema["server"]),
                           ("SettingsMessage", {k: v for k, v in schema["client"].items() if "settings" in v["surfaces"]})]:
        types += f"export type {name} =\n  | {union(messages)};\n"
    types += '''declare global {
  var MsimeProtocol: {
    validate(message: unknown, direction: 'client' | 'server', surface?: string): boolean;
    serializeClientMessage(message: ClientMessage, surface: string): string;
    version: number;
  };
}
export function serializeHostMessage(message: SettingsMessage): string {
  return globalThis.MsimeProtocol.serializeClientMessage(message, 'settings');
}
export function isServerMessage(message: unknown): message is ServerMessage {
  return globalThis.MsimeProtocol.validate(message, 'server');
}
'''
    files["messages.ts"] = types
    files["schema.d.ts"] = "export {};\n"
    return files


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for name, content in generate().items():
        path = ROOT / name
        payload = content.encode("utf-8")
        if args.check:
            # Byte comparison, not read_text(): text mode folds CRLF to LF and
            # would hide a line-ending drift in an otherwise identical file.
            if not path.exists() or path.read_bytes() != payload:
                raise SystemExit(f"Stale binding: {path}; run generate.py")
        else:
            # newline="\n" keeps the checked-in bytes platform-independent; text
            # mode's default translation writes CRLF on Windows.
            path.write_text(content, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
